## Kitty minimal Conf
# Fonts 
font_size 11.0

# Bindings
map ctrl+tab next_tab
map cmd+tab next_tab
map cmd+shift+l next_tab
map ctrl+shift+l next_tab

map ctrl+shift+tab previous_tab
map cmd+shift+tab previous_tab
map cmd+shift+h previous_tab
map ctrl+shift+h previous_tab

# Misc
scrollbar_lines 10000
scrollbar scrolled-and-hovered

tab_title_wrap 30
tab_title_template "{tab.progress_percent}{tab.active_exe} - {tab.active_wd}"

